### ISSUE TITLE
Conventional Commits

### ISSUE THREAD

**Issue by kostyaten** [best-doctor/guides#33]
Вы смотрели на практику Conventional Commits в качестве guide commit ?
Для pycharm есть плагин - https://plugins.jetbrains.com/plugin/13389-conventional-commit

Сайт - https://www.conventionalcommits.org/

**Comment by Arondit** [comment]
@kostyaten 

Спасибо за вопрос, после него мы задумались об этом всерьез (да, мы заметили и обсудили его несколько запоздало). 

Conventional commit нам не совсем подходит, поэтому мы решили написать свой гайд по коммит-сообщениям, вот он https://github.com/best-doctor/guides/blob/master/guides/commit_messages_guide.md
